disabled_rules:
  - trailing_whitespace
  - force_unwrapping                   # Allow force unwrapping for low-level operations
  - implicitly_unwrapped_optional     # Common in Cocoa UI development
  - vertical_whitespace_opening_braces # Relaxed formatting for AI-generated code
  - vertical_whitespace_closing_braces # Relaxed formatting for AI-generated code
  - function_parameter_count          # Media functions can have many parameters
  - vertical_parameter_alignment      # Relaxed alignment rules
  - duplicate_imports                 # May be needed in some cases
  - todo                             # Allow TODOs in development
  - trailing_comma                   # Flexible on trailing commas
  - for_where                        # Allow traditional for-if patterns

opt_in_rules:
  - empty_count
  - empty_string
  - overridden_super_call
  - redundant_nil_coalescing
  - syntactic_sugar

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Package.swift

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 500
  error: 1000

file_length:
  warning: 500
  error: 1500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - id
    - url
    - uri
    - CSS_KEY_SIZE
    - SECTOR_SIZE
    - DVD_BLOCK_LEN
    - AACS_KEY_SIZE
    - AES_BLOCK_SIZE
    - BLURAY_BLOCK_LEN
    - VIDEO_TS_PATH
    - IFO_EXTENSION
    - VOB_EXTENSION
    - BUP_EXTENSION
    - BDMV_PATH
    - PLAYLIST_PATH
    - STREAM_PATH
    - CLIPINF_PATH
    - AUXDATA_PATH

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

reporter: "xcode"
