disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - file_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - syntactic_sugar
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Package.swift

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1200

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - id
    - url
    - uri

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

reporter: "xcode"
